### PR TITLE
Fix magnet card not working in wireless universal terminal

### PR DESCRIPTION
**Pull request by starforcraft**

### CODE REVIEW

**Comment by Mari023** [comment]
the wireless universal terminal is already ticking all installed terminals, this shouldn't be necessary.

using a debugger, it seems like ItemWUT#inventoryTick() is never even called, instead it directly jumps to your WirelessTerminalItem mixin.

I don't think there is anything that can be done about that in ae2wtlib, and I don't know how this could be fixed  in AE2-Insert-Export-Card either.

**Comment by starforcraft** [comment]
No, that is not true. After some debugging, I realised that the magnet upgrade doesn't work at all even without the AE2 Insert Export Card mod in a universal terminal. This is because the inventoryTick() method from the IUniversalWirelessTerminalItem interface in the mixin  is not getting called

**Comment by starforcraft** [comment]
https://github.com/Mari023/AE2WirelessTerminalLibrary/blob/a18359f4266b22968b7763204cf507a3dce07398/src/main/java/de/mari_023/ae2wtlib/wut/ItemWUT.java#L96

In the 1.19.2 branch you still had these lines of code in the ItemWUT class, which this PR adds back

**Comment by Mari023** [comment]
> The weird thing is that after some debugging, I realised that the magnet upgrade doesn't work at all even without the AE2 Insert Export Card mod in a universal terminal for some reason

I just retested it, as long as you have a wireless crafting terminal in the universal terminal, the magnet card works with just ae2wtlib

> In the 1.19.2 branch you still had these lines of code in the ItemWUT class, which this PR adds back

those lines are no longer necessary, in 1.20.1+ it loops over all possible terminals, and calls the inventoryTick method of them if the universal terminal has the terminal

**Comment by starforcraft** [comment]
https://imgur.com/a/C89FZoy

Installed mods:
ae2wtlib-15.2.2-forge
appliedenergistics2-forge-15.0.23
architectury-9.2.14-forge
cloth-config-11.1.118-forge
curios-forge-5.7.2+1.20.1

**Comment by Mari023** [comment]
I did some more testing, it turns out it only works if a specific set of terminals is installed (crafting + pattern encoding worked, crafting + pattern encoding didn't, having all possible terminals installed means it is guaranteed to work).
looking at the code, it is also obvious why that happens:
https://github.com/Mari023/AE2WirelessTerminalLibrary/blob/5dff341b674091a01b55089dc48dd7e73f16b605/src/main/java/de/mari_023/ae2wtlib/wut/ItemWUT.java#L95-L96

the fix for this is trivial (e46f139041b2ecdb69c970c591051ab1eca3a5c2), but it won't solve the issue where AE2-Insert-Export-Card somehow breaks all ticking in the wireless universal terminal

**Comment by starforcraft** [comment]
Wow, how could I have missed that 😂 That was such a simple yet effective change. I did some tests and the issue seems to be solved now. The insert/export card now work fine together with the magnet card. (I mixin in `WirelessTerminalItem` and you in `WirelessCraftingTerminalItem`, which is why there is no problem)

**Pull request closed without merging**
