### PR TITLE
call ticking magnet and restock from Item#tick

### LINKED ISSUE #150: A matter of life and coding
In order for the magnetic card to work we call "doMagnet" EVERY SERVER TICK?
I understand correctly?

### LINKED ISSUE #153: Hmm... more warnings in logs...
image

### PR DESCRIPTION
**Pull request by Mari023**
...instead of from server tick
fix #150 
works with and without  trinkets

also fixes #153

### CODE REVIEW

**Comment by Domaman202** [comment]
Okay, once this push is done, I'll go ahead and execute #144

**Comment by Mari023** [comment]
> Okay, once this push is done, I'll go ahead and execute #144

Thanks for offering help, but I would prefer to do that myself.
There are still some parts of it which I am not sure about

**Comment by Domaman202** [comment]
Ok :^

**Comment by Domaman202** [comment]
And how to check the operation of a magnetic card? xD

**Comment by Mari023** [comment]
> And how to check the operation of a magnetic card? xD

drop an item, activate the card (either via the gui or via a hotkey)
I am not sure if the default is using a blacklist or a whitelist, you might have to configure it in the gui

**Pull request merged**
